fix: populate stac metadata hrefs with relative links
linz/topo-processor pull request #276
Opened 2021-07-05 21:06 UTC by MDavidson17

2021-07-08 02:25 UTC, blacha approved these changes

2021-07-08 03:13 UTC, paulfouquet commented on topo_processor/util/transfer_collection.py
> +    stac_collection.set_self_href("./collection.json")
I would recommend setting this in the collection.create_stac() function. What do you think?

2021-07-08 05:02 UTC, paulfouquet requested changes
topo_processor/cli/tests/main_test.py
As you've modified this file, could you please remove line 26?

Also, check my comment on transfer_collection.py

2021-07-12 23:06 UTC, paulfouquet approved these changes

2021-07-12 23:39 UTC, merged