feat: configuration for li topo deployment TDE-173
linz/topo-processor pull request #571
Opened 2022-02-13 19:27 UTC by amfage

2022-02-13 21:06 UTC, blacha approved these changes

2022-02-13 21:57 UTC, blacha requested changes

2022-02-13 21:57 UTC, blacha commented on infra/src/submit.ts
> -    { name: 'LDS_CACHE_BUCKET', value: 'linz-lds-cache' },
We need this environment variable

2022-02-14 00:08 UTC, paulfouquet approved these changes
:+1:

2022-02-15 00:53 UTC, closed without merging