feat: tde-243 validate collection
linz/topo-processor pull request #788
Opened 2022-04-11 03:53 UTC by amfage

2022-04-11 04:03 UTC, paulfouquet requested changes

2022-04-11 04:03 UTC, paulfouquet commented on topo_processor/metadata/metadata_validators/metadata_validator_stac.py
> +    def validate_metadata_pystac_collection(self, collection: PystacCollection) -> None:
You should re-use the existing `validate_metadata` method (change the signature and refactor the callers) to avoid code duplication here.

2022-04-12 20:44 UTC, paulfouquet approved these changes

2022-04-18 21:03 UTC, MDavidson17 approved these changes

2022-04-25 20:58 UTC, merged